sudo: required
services:
  - docker

before_install:
  - docker build -t nareshk101/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run nareshk101/react-test npm test -- --coverage
after_sucess:
  - docker build -t nareshk101/multi-client ./client
  - docker build -t nareshk101/multi-ngnix ./ngnix
  - docker build -t nareshk101/multi-server ./server
  - docker build -t nareshk101/muti-worker ./worker
 
 # Login into docker CLI

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 # Take thise images abd push them to docker hub
 - docker push nareshk101/muti-client
 - docker push nareshk101/multi-ngnix
 - docker push nareshk101/multi-server
 - docker push nareshk101/multi-worker